### ISSUE TITLE
Error with namespace prefix t3

### ISSUE THREAD

**Issue by msollmann** [evoWeb/ew_llxml2xliff#10]
When opening a record folder with records whose labels are converted to xliff the list module says:

> PHP Warning: simplexml_load_string(): namespace error : Namespace prefix t3 for id on file is not defined in /typo3_src-11.5.6/typo3/sysext/core/Classes/Localization/Parser/AbstractXmlParser.php line 116

Do we really need the t3:id attribute in the file node?
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Internationalization/XliffFormat.html
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1094

**Comment by garbast** [comment]
Please test the develop branch, if the problem is fixed.

**Comment by msollmann** [comment]
Great, it works!

**Comment by msollmann** [comment]
Can you publish the new version? I forgot about the error and used the buggy TER version again, in another project...

**Comment by opi99** [comment]
👍

**Comment by 720720** [comment]
could you please publish the new version to the TER

**Comment by garbast** [comment]
Released with tag 4.1
