### ISSUE TITLE
feature: conversion to new XLIFF format

### ISSUE THREAD

**Issue by franzholz** [evoWeb/ew_llxml2xliff#11]
The format of the XLIFF file has changed.
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Internationalization/XliffFormat.html?highlight=translation%20file

So a conversion would be needed from old XLIFF format to new XLIFF format.
It is a lot of work to do this manually for each file.

Do you agree to such an improvement? 
Should I provide this?

**Comment by franzholz** [comment]
The current conversion from XML to XLIFF does not convert to the format of the TYPO3 documentation.

`<trans-unit id="generator" resname="generator">`

**Comment by franzholz** [comment]
At the moment seems that I cannot use this extension any more in the current state.
The extensions have already converted the XML files into XLIFF years ago. All the translations lie on the translation server. Now they shall come to the Crowdin server. 
According to another case you rejected, I am forced to reconstruct all language specific files into one big XML file. But I do not have the original English XML file any more. 
So this extension is unusable for this case where the translation files must be moved.

**Comment by garbast** [comment]
It does what it promises and it is only intended for a limited use case. It was never intended to be used for xliff to crowdin conversion.

I'm sorry to hear, that it does not fullfill your specific need, but the scope will not be broadned.
