### ISSUE TITLE
Error on not loaded EXTs

### ISSUE THREAD

**Issue by ste101** [evoWeb/ew_llxml2xliff#14]
There will be an error on every not loaded EXT, e.g.:
TYPO3 Fatal Error: Extension key "felogin" is NOT loaded!

Version 5.0.0
TYPO3 12.4.5
PHP 8.2

Version 4.1.0
TYPO3 11.5.29

**Comment by garbast** [comment]
Felogin is not used in this extension at all. So were do you expect the extension to help?

If for what ever reason you do use it with a non composer based installation, stop doing so.

**Comment by garbast** [comment]
Closed due to inactivity

**Comment by SventB** [comment]
Same here.

> If for what ever reason you do use it with a non composer based installation, stop doing so.

So you say your extension is not working on non composer based installation?

Can be easily fixed:

```php
                try {
                    if (count($this->getFilesOfExtension($extension['key']))) {
                        $extensionsWithFileToConvert[] = $extension;
                    }
                    return count($extensionsWithFileToConvert);
                } catch (\Exception) {
                }
```

**Comment by SventB** [comment]
Ok, seems to work only with composer:


> (1/1) #1631700480 BadMethodCallException
> Composer root path is only available in Composer mode

**Comment by garbast** [comment]
> 
> So you say your extension is not working on non composer based installation?
> 

YES! And also i say, we have 2024 stop using non composer installations. Or stop using my extensions. But don't complain, that they don't do what you want them to do.

**Comment by SventB** [comment]
I do not complain.

This is a little bit misleading: https://github.com/evoWeb/ew_llxml2xliff/blob/develop/Documentation/Installation/Index.rst#download-via-extension-manager

**Comment by garbast** [comment]
You are right. I corrected that bit. Thank's for pointing that out.
