### ISSUE TITLE
CSP Error

### ISSUE THREAD

**Issue by steffen-hph** [evoWeb/ew_llxml2xliff#15]
If the setting "[SYS][features][security.backend.enforceContentSecurityPolicy]" is active, the backend module does not work anymore.

Currently easy to solve by temporarily deactivating the setting.

TYPO3: 12.4.7
ew_llxml2xliff: 5.0.0 (GitHub: 2023-10-25)

![image](https://github.com/evoWeb/ew_llxml2xliff/assets/78363413/2d6e3148-09df-4f2c-a015-dfeb501814e0)

**Comment by garbast** [comment]
Resolved with Commit #d4b2e55
