### ISSUE TITLE
BadFunctionCallException is thrown for not activated extensions

### ISSUE THREAD

**Issue by franzholz** [evoWeb/ew_llxml2xliff#16]
See class ExtensionManagementUtility:

    public static function extPath(string $key, string $script = ''): string
    {
        if (!static::$packageManager->isPackageActive($key)) {
            throw new \BadFunctionCallException('TYPO3 Fatal Error: Extension key "' . $key . '" is NOT loaded!', 1365429656);
        }
        return static::$packageManager->getPackage($key)->getPackagePath() . $script;
   
Solution:

    public function getFilesOfExtension(string $extensionKey): array
    {
        // try {
        //     $extensionPath = ExtensionManagementUtility::extPath($extensionKey);
        // } catch (\Exception $e) {
        //     debug ($e, 'getFilesOfExtension EXCEPTON $e');
        // }

        $extensionPath = GeneralUtility::getFileAbsFileName('EXT:' . $extensionKey. '/ext_emconf.php'); 
        if (empty($extensionPath)) {
            return [];
        }
        $extensionPath = dirname($extensionPath). '/';
        $files = GeneralUtility::getAllFilesAndFoldersInPath([], $extensionPath, 'php,xml', 0);

**Comment by garbast** [comment]
And by the way. Stop using non composer setups.
