### ISSUE TITLE
Make translated files convertable

### ISSUE THREAD

**Issue by franzholz** [evoWeb/ew_llxml2xliff#6]
I want to convert the file en.locallang.xml into en.locallang.xlf. Extension addons_tt_products.
But I get the error message:

```
File "en.locallang.xml" in extension "addons_tt_products" couldn't be converted automatically

ERROR: Filename didn't start with "locallang".
```

Please remove the restriction which disallows this.

ew_llxml2xliff/Classes/Utility/Convert.php:

    protected function checkLanguageFilename(string $xmlFile): string
    {
        $basename = basename($xmlFile);

        $result = '';
        if (strpos($basename, 'locallang') !== 0) {
            $result = 'ERROR: Filename didn\'t start with "locallang".';
        }
        return $result;
    }

**Comment by franzholz** [comment]
Proposal:

    protected function checkLanguageFilename(string $xmlFile): string
    {
        $result = '';
        if (strpos($xmlFile, 'locallang') === false) {
            $result = 'ERROR: Filename didn\'t contain "locallang".';
        }
        return $result;
    }

**Comment by garbast** [comment]
First of, please hand i your proposal as PR. Second the change has shortcomings, as the result would be a en.en.locallang.xlf which is not valid.

Just change one condition does not solve the problem. For a quickfix for your case, it would be enough to add all <languageKey index="*" type="array"> nodes in the locallang.xml and convert them in one go.

**Comment by franzholz** [comment]
I think that another patch must be written.

`			<trans-unit id="basket_into" xml:space="preserve" approved="yes">
				<source>Dans le panier.</source>
				<target>Dans le panier.</target>
			</trans-unit>
`

The 'source' tag must be in English.
How can this be accomplished? The file in English language must be considered.

**Comment by garbast** [comment]
I dont consider this as usefull to the broader user base. You need to assume the locallang.xml as present and read it, then merge both languages into one array only to write it back in separate files.

And here i will draw the line and refuse to merge and PR that is trying to merge language and default to write it back.

**Comment by franzholz** [comment]
It is too much work to edit the XLF files manually.

**Comment by garbast** [comment]
You should not edit the XLF but the XML file manually. Open the locallang.xml and copy all the <languageKey index="en" type="array">, <languageKey index="es" type="array"> etc nodes into it. Then convert the locallang.xml enblock so that all translations get written in their *.locallang.xlf files.

**Comment by franzholz** [comment]
Yes, your way is the only practicable solution at the moment. Otherwise I would sit for several hours on these language files. Otherwise a second patch would be needed which converts the language specific file together with the original English file into the XLF format.
